# !/usr/bin python3.8                                
# encoding: utf-8 -*-                            
# @author: ninghui_hiahia
# @Time: 2022/3/26  5:11 下午
import jsonpath


s={"trade_sn":"20220306000052","member_id":59,"member_name":"shamo","payment_t ype":"COD","price_detail": {"total_price":179.0,"original_price":179.0,"goods_price":179.0,"freight_pri ce":0.0,"discount_price":0.0,"cash_back":0.0,"coupon_price":0.0,"full_minus" :0.0,"is_free_freight":0,"exchange_point":0},"consignee": {"consignee_id":3716,"name":"金枝","province":"北京","city":"朝阳 区","county":"三环以内","town":None,"address":"北 京","mobile":"18888888888","telephone":None,"province_id":1,"county_id":2799 ,"city_id":72,"town_id":0},"coupon_list":None,"order_list": [{"seller_id":20,"shipping_type_id":None,"shipping_type_name":None,"seller_n ame":"沙陌的店","weight":2.0,"price": {"total_price":179.0,"original_price":179.0,"goods_price":179.0,"freight_pri ce":0.0,"discount_price":0.0,"cash_back":0.0,"coupon_price":0.0,"full_minus" :0.0,"is_free_freight":0,"exchange_point":0},"sku_list": [{"seller_id":20,"seller_name":"沙陌的 店","goods_id":4942,"sku_id":5173,"sku_sn":"shamo001","cat_id":83,"num":1,"p urchase_num":0,"goods_weight":2.0,"original_price":179.0,"purchase_price":179.0,"subtotal":179.0,"name":"沙陌**炒 锅","goods_image":"http://www.mtxshop.com:7000/statics/attachment/goods/2021 /12/13/21/50442449.png_300x300.png","template_script":None,"checked":1,"is_f ree_freight":1,"single_list":[],"group_list":[],"promotion_tags": [],"not_join_promotion":0,"template_id":0,"spec_list":None,"point":None,"sna pshot_id":None,"service_status":"NOT_APPLY","last_modify":1640517899,"enable _quantity":9998714,"rule":None,"invalid":0,"error_message":"","is_ship":1,"g oods_type":"NORMAL"}],"gift_list":[],"gift_coupon_list": [],"gift_point":None,"invalid":None,"trade_sn":"20220306000052","sn":"20220306000052","consignee":{"consignee_id":3716,"name":"金枝","province":"北 京","city":"朝阳区","county":"三环以内","town":None,"address":"北 京","mobile":"18888888888","telephone":None,"province_id":1,"county_id":2799 ,"city_id":72,"town_id":0},"shipping_id":0,"payment_type":"COD","ship_time": None,"receive_time":"任意时 间","member_id":59,"member_name":"shamo","remark":"","create_time":1646538406,"shipping_type":None,"order_status":"NEW","pay_status":"PAY_NO","ship_stat us":"SHIP_NO","ship_name":None,"order_price":179.0,"shipping_price":None,"co mment_status":"UNFINISHED","disabled":None,"payment_method_id":None,"payment _plugin_id":None,"payment_method_name":None,"payment_account":None,"goods_nu m":1,"warehouse_id":None,"cancel_reason":None,"ship_province_id":None,"ship_ city_id":None,"ship_region_id":None,"ship_town_id":None,"ship_province":None ,"ship_city":None,"ship_region":None,"ship_town":None,"signing_time":None,"t he_sign":None,"admin_remark":None,"address_id":None,"need_pay_money":179.0," ship_no":None,"logi_id":None,"logi_name":None,"need_receipt":0,"receipt_titl e":None,"receipt_content":None,"service_status":"NOT_APPLY","client_type":"P C","receipt_history":None,"order_type":"NORMAL","order_data":None,"goods_cou pon_prices":None}],"gift_list":None}

trade_sn=jsonpath.jsonpath(s,'$.trade_sn')
print(trade_sn)
sn=jsonpath.jsonpath(s,'$..sn')
print(sn)
total_price=jsonpath.jsonpath(s,'$.price_detail.total_price')
print(total_price)
print('---------------------------------------------------------')
#
# res={'order_id': 75831, 'trade_sn': '20220326000211', 'seller_id': 20, 'seller_name': '沙陌的店', 'member_id': 59, 'member_name': 'shamo', 'order_status': 'CONFIRM', 'pay_status': 'PAY_NO', 'ship_status': 'SHIP_NO', 'shipping_id': 0, 'comment_status': 'UNFINISHED', 'shipping_type': None, 'payment_method_id': None, 'payment_plugin_id': None, 'payment_method_name': None, 'payment_type': 'COD', 'payment_time': None, 'pay_money': None, 'ship_name': 'shamonew', 'ship_addr': '北京市昌平区回龙观国风美唐', 'ship_zip': None, 'ship_mobile': '15510496222', 'ship_tel': None, 'receive_time': '仅工作日', 'ship_province_id': 1, 'ship_city_id': 72, 'ship_county_id': 2799, 'ship_town_id': 0, 'ship_province': '北京', 'ship_city': '朝阳区', 'ship_county': '三环以内', 'ship_town': '', 'order_price': Decimal('179.00'), 'goods_price': Decimal('179.00'), 'shipping_price': Decimal('0.00'), 'discount_price': Decimal('0.00'), 'disabled': 0, 'weight': Decimal('2.00'), 'goods_num': None, 'remark': '', 'cancel_reason': None, 'the_sign': None, 'items_json': '[{"seller_id":20,"seller_name":"沙陌的店","goods_id":4942,"sku_id":5173,"sku_sn":"shamo001","cat_id":83,"num":1,"goods_weight":2.0,"original_price":179.0,"purchase_price":179.0,"subtotal":179.0,"name":"沙陌**炒锅","goods_image":"http://www.mtxshop.com:7000/statics/attachment/goods/2021/12/13/21/50442449.png_300x300.png","spec_list":null,"point":null,"snapshot_id":null,"service_status":"NOT_APPLY","complain_status":"NO_APPLY","complain_id":null,"single_list":[],"group_list":[],"goods_operate_allowable_vo":null,"promotion_tags":[],"purchase_num":0,"actual_pay_total":179.0}]', 'warehouse_id': None, 'need_pay_money': Decimal('179.00'), 'ship_no': None, 'address_id': 3896, 'admin_remark': None, 'logi_id': None, 'logi_name': None, 'complete_time': None, 'create_time': 1648298781, 'signing_time': None, 'ship_time': None, 'pay_order_no': None, 'service_status': 'NOT_APPLY', 'bill_status': None, 'bill_sn': None, 'client_type': 'MINI', 'sn': '20220326000211', 'need_receipt': 0, 'order_type': 'NORMAL', 'order_data': None}
# items_json=res['items_json']
# print(items_json)